### ISSUE TITLE
pointer problem

### ISSUE THREAD

**Issue by AbrahamGitHubCat** [dharmik2319/geotastic-helper#7] opened 2024-09-12 17:53 UTC
THERES NO POINTER !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! PLZ 
HELP 
i download all the steps from the github page

**Comment by dharmik2319** [comment] 2024-09-15 06:18
duplicate of #3.

**Closed** 2024-09-15 06:20 UTC
